flixter/config/routes.rb
Flixter::Application.routes.draw do
  devise_for :users
  root 'static_pages#index'
  namespace :instructor  do
    resources :courses, :only => [:new, :create, :show]

  end

end

flixter/app/models/course.rb
class Course < ActiveRecord::Base
	belongs_to :user
end

flixter/app/models/user.rb
class User < ActiveRecord::Base
	has_many :course
  	# Include default devise modules. Others available are:
  	# :confirmable, :lockable, :timeoutable and :omniauthable
  	devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

flixter/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

flixter/app/controllers/instructor/courses_controller.rb
class Instructor::CoursesController < ApplicationController
  before_action :authenticate_user!

  def new
    @course = Course.new
  end

  def create
    @course = current_user.courses.create(course_params)
    redirect_to instructor_course_path(@course)
  end

  def show
    @course = Course.find(params[:id])
  end

  private

  def course_params
    params.require(:course).permit(:title, :description, :cost)
  end
end

flixter/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

def index
end

end

flixter/app/helpers/application_helper.rb
module ApplicationHelper
end

flixter/app/helpers/instructor/courses_helper.rb
module Instructor::CoursesHelper
end

flixter/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

flixter/app/views/instructor/courses/new.html.erb
<br />
<div class="booyah-box col-xs-10 col-xs-offset-1">
  <h1>Add a new course</h1>
  <%= simple_form_for @course, :url => instructor_courses_path do |f| %>
    <%= f.input :title %>
    <%= f.input :description %>
    <%= f.input :cost %>
    <br />
    <%= f.submit "Create", :class => 'btn btn-primary' %>
    <br />
  <% end %>
  <br />
</div>

flixter/app/views/instructor/courses/show.html.erb
<br />
<div class="booyah-box col-xs-10 col-xs-offset-1">
  <h1 class="text-center"><%= @course.title %></h1>
</div>

flixter/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Flixter</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div id="wrap">
    <nav class="navbar navbar-inverse" role="navigation">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to 'Flixter', root_url, :class => 'navbar-brand' %>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li><a href="#">Link</a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li><a href="#">Link</a></li>
            <% if user_signed_in? %>
              <li><%= link_to 'Sign out', destroy_user_session_path, :method => :delete %></li>
            <% else %>
              <li><%= link_to 'Sign in', new_user_session_path %></li>
              <li><%= link_to 'Sign up', new_user_registration_path %></li>
            <% end %>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>


    <% if notice.present? %>
      <p class="alert alert-info"><%= notice %></p>
    <% end %>

    <% if alert.present? %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>

    <%= yield %>

  </div>

   <br class="clr" />

  <div id="footer">
    <div class="container">
      <b>Teachers</b>
      <br />
      <%= link_to 'Teach a Course', new_instructor_course_path %>
    </div>
  </div>

</body>
</html>

flixter/app/views/static_pages/index.html.erb
<div class="hero">
  <br />
  <div class="frosty col-xs-10 col-xs-offset-1 text-center">
    <br />
    <h1>Learn Magic from the Pros</h1>
    <br />
    <h2>I'm an illusionist, Michael.</h2>
    <br />
    <%= link_to 'Learn More', '#', :class => 'btn btn-success' %>
    <br /><br />
  </div>
</div>

<br />
<div class="col-xs-10 col-xs-offset-1 features text-center">
  <div class="col-sm-4">
    <h3>Feature 1</h3>
  </div>

  <div class="col-sm-4">
    <h3>Feature 2</h3>
  </div>

  <div class="col-sm-4">
    <h3>Feature 3</h3>
  </div>
</div>